/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import MoonbaseLogoImage from './assets/images/MoonbaseLogo.png';
import MoonbaseLogoMImage from './assets/images/MoonbaseLogo_M.png';
import Avatar1Image from './assets/images/Avatar.png';
import { styled } from '@mui/material/styles';
import SidebarRow1 from '"/"/SidebarRow1';

 
const CollapsableOpen = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: `700px`,  
  width: `290px`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `16px`,  
  boxSizing: `border-box`,  
});
  
const Top = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `20px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `482.5px`,  
});
  
const Logo = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 0px 0px 40px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const MoonbaseLogo = styled("img")({  
  height: `14.22px`,  
  width: `128px`,  
  margin: `0px`,  
});
  
const MoonbaseLogoM = styled("img")({  
  height: `11px`,  
  width: `9px`,  
  margin: `0px`,  
});
  
const List = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `56px 0px 0px 0px`,  
});
  
const SidebarRow11 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `0px`,  
}));
  
const SidebarRow12 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow13 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow14 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow15 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow16 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow17 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const SidebarRow18 = styled(SidebarRow1)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `40px`,  
  margin: `10px 0px 0px 0px`,  
}));
  
const Account = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
});
  
const Divide = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const DividerHorizontal = styled("div")({  
  border: `1px solid rgba(0, 0, 0, 0.12)`,  
  boxSizing: `border-box`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Btm = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 30px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `8px 0px 0px 0px`,  
});
  
const Avatar1 = styled("img")({  
  height: `32px`,  
  width: `32px`,  
  margin: `0px`,  
});
  
const EllenCho = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(53, 53, 53, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
 
function Sidebar1(props) {
  return (
    <CollapsableOpen >
       <Top >
         <Logo >
           <MoonbaseLogo  src={MoonbaseLogoImage} alt={"MoonbaseLogo"}/>
           {false &&
               <MoonbaseLogoM  src={MoonbaseLogoMImage} alt={"MoonbaseLogo_M"}/>
           }
         </Logo>
         <List >
           <SidebarRow11   />
           <SidebarRow12   />
           <SidebarRow13   />
           <SidebarRow14   />
           {(false) &&
               <SidebarRow15   />
           }
           {(false) &&
               <SidebarRow16   />
           }
           {(false) &&
               <SidebarRow17   />
           }
           {(false) &&
               <SidebarRow18   />
           }
         </List>
       </Top>
       <Account >
         <Divide >
           <DividerHorizontal >
           </DividerHorizontal>
         </Divide>
         <Btm >
           <Avatar1  src={Avatar1Image} alt={"Avatar"}/>
           <EllenCho >
             {`Ellen Cho`}
               </EllenCho>
         </Btm>
       </Account>
     </CollapsableOpen>
   );
}

export default Sidebar1;
